using System;

class TryCatch
{
    public void SetData()
    {
        Console.WriteLine("Enter first number:");
        int x1 = Int32.Parse(Console.ReadLine());
        Console.WriteLine("Enter second number:");
        int x2 = Int32.Parse(Console.ReadLine());

        try
        {
            int res = x1 / x2;
            Console.WriteLine("Division is: " + res);
        }
        catch (DivideByZeroException d)
        {
            Console.WriteLine("Error occurred: " + d.Message);
        }
        finally
        {
            Console.WriteLine("This is out of the try-catch block.");
        }
    }
}

class Program
{
    public static void Main(string[] args)
    {
        TryCatch t = new TryCatch();
        t.SetData();
    }
}
